config/routes.rb
Omrails::Application.routes.draw do
  get "users/show"
  resources :pins

  devise_for :users
  get 'users/:id' => 'users#show', as: :user

  get "pages/test"

get 'about' => 'pages#about'
get 'test' => 'pages#test'
root :to => 'pins#index'

end

app/models/pin.rb
class Pin < ActiveRecord::Base
	belongs_to :user
	has_attached_file :image, styles: { thumb: "150x150>"}

	attr_accessible :description, :image, :image_remote_url

	validates :description, presence: true
	validates :user_id, presence: true
	validates_attachment :image, presence: true,
								content_type: { content_type: ['image/jpg', 'image/jpeg', 'image/png', 'image/gif']},
								size: {less_than: 5.megabytes}
	def image_remote_url=(url_value)
		self.image = URI.parse(url_value) unless url_value.blank?
		super
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  attr_accessible  :name, :email, :password, :password_confirmation, :remember_me, :provider, :uid, :as => [:default, :admin]

has_many :pins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def test
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_filter :authenticate_user!, except: [:index]
  before_action :set_pin, only: [:show, :edit, :update, :destroy]

  # GET /pins
  def index
    @pins = Pin.order("created_at desc").page(params[:page]).per_page(20)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pins }
      format.js
    end
  end

  # GET /pins/1
  def show
  end

  # GET /pins/new
  def new
    @pin = current_user.pins.new 
  end

  # GET /pins/1/edit
  def edit
    @pin = current_user.pins.find(params[:id])
  end

  # POST /pins
  def create
    @pin = current_user.pins.new (params[:pin])

    if @pin.save
      redirect_to @pin, notice: 'Pin was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /pins/1
  def update
    @pin = current_user.pins.find(params[:id])
    if @pin.update(pin_params)
      redirect_to @pin, notice: 'Pin was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /pins/1
  def destroy
    @pin = current_user.pins.find(params[:id])
    @pin.destroy
    redirect_to pins_url, notice: 'Pin was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def pin_params
      params.require(:pin).permit(:description)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @pins = @user.pins.page(params[:page]).per_page(20)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">
			<small>
				<%= link_to "One Month Rails", "http://onemonthrails.com" %>
			by <%= link_to "Spencer Handley", "http://spencerhandley.me" %>
			</small>

		</div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
 
      <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
 
      <!-- Be sure to leave the brand out there if you want it shown -->
      <%= link_to "One Month Rails", root_path, class: "brand" %>
 
      <!-- Everything you want hidden at 940px or less, place within here -->
      <div class="nav-collapse collapse">
      	<ul class="nav">
        	<li><%= link_to "Home", root_path %></li>
			<li><%= link_to "About", about_path %></li>
			<li><%= link_to "Test", test_path %></li>
		</ul>
		<ul class="nav pull-right">
      <% if user_signed_in? %>
        <li><%= link_to "Add +", new_pin_path%></li>
        <li><%= link_to "Edit Profile", edit_user_registration_path%></li>
        <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
        <% else %>
        	<li><%= link_to "Login", new_user_session_path %></li>
      <% end %>    
		</ul>
		
      </div>
 
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Omrails</title>
	  <%= stylesheet_link_tag    "application", :media => "all" %>
	  <%= javascript_include_tag "application" %>
	  <%= csrf_meta_tags %>
	</head>
	<body>
		<%= render 'layouts/header' %>

		<div class="container">
			<% flash.each do |name, msg| %>
				<%= content_tag(:div, msg, class: "alert alert-#{name}") %>
				<% end %>

		<%= yield %>
		
		<%= render 'layouts/footer' %>
	</div>

	</body>
</html>

app/views/pages/_home.html.erb
<% if user_signed_in? %>
	<h1> You're logged in! </h1>
<% else %>
<div class="hero-unit">
      <h1>Welcome to One Month Rails</h1>
	<p>You've found the homepage for the
		<%= link_to "One Month Rails", "http://onemonthrails.com"%>
			application.
	</p>
	<p>
	<%= link_to "Sign Up Now!", new_user_registration_path, class: "btn btn-primary btn-large" %>
	</p>
    
</div>
<% end %>

app/views/pages/about.html.erb
<h1>About</h1>
<p>
	<%= link_to "One Month Rails", "http://onemonthrails.com" %>
	is that project to teach 
	<%= link_to "Ruby On Rails", "http://rubyonrails.com" %>
	in one month. this is a sample application.
</p>

app/views/pages/home.html.erb
<% if user_signed_in? %>
	<h1> You're logged in! </h1>
<% else %>
<div class="hero-unit">
      <h1>Welcome to One Month Rails</h1>
	<p>You've found the homepage for the
		<%= link_to "One Month Rails", "http://onemonthrails.com"%>
			application.
	</p>
	<p>
	<%= link_to "Sign Up Now!", new_user_registration_path, class: "btn btn-primary btn-large" %>
	</p>
    
</div>
<% end %>

app/views/pages/test.html.erb
Test

app/views/pins/_form.html.erb
<%= simple_form_for(@pin, html: {class: "form_horizontal"}) do |f| %>
  <%= f.error_notification %>
  <%= f.full_error :image_file_size, class: "alert alert-error" %>
  <%= f.full_error :image_content_type, class: "alert alert-error" %>

	<%= f.input :image, label: "Upload an Image" %>
	<%= f.input :image_remote_url, label: "or Enter a URL" %>
    <%= f.input :description, as: :text, input_html: { rows: "3"} %>


  <div class="actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/pins/_pin.html.erb
<div class="box">
    <%= link_to (image_tag pin.image(:thumb)), pin %>
    <p class="description">
        <%= pin.description %>
    </p>
    <p>
<strong>
            Posted by <%= link_to pin.user.name, pin.user %>
        </strong>
    </p>
    <% if current_user == pin.user %>
        <p>
          <%= link_to 'Edit', edit_pin_path(pin) %>
          <%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure?' } %>
        </p>
    <% end %>
</div>

app/views/pins/edit.html.erb
<h1>Editing pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<%= render 'pages/home' %>

<div id="pins">
  <%= render @pins %>
</div>
 <%= will_paginate @pins %>

app/views/pins/index.js.erb
$boxes = $('<%= j render(@pins) %>')

$('#pins').append( $boxes ).imagesLoaded( function(){
    $('#pins').masonry( 'reload');
});
<% if @pins.next_page %>
    $('.pagination').replaceWith('<%= j will_paginate(@pins) %>');
<% else %>
    $('.pagination').remove();
<% end %>

app/views/pins/new.html.erb
<h1>New pin</h1>

<%= render 'form' %>

<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
<div class="row">
	<div class="span6 offset3">
		<div class="well">
			<%= image_tag @pin.image %>
			<p>
				<%= @pin.description %>
			</p>
			<p>
				<%= @pin.user.name %>
			</p>
				<% if current_user == @pin.user %>

					<%= link_to 'Edit', edit_pin_path(@pin) %> |
				<% end %>
					<%= link_to 'Back', pins_path %>

		</div>
	</div>
</div>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>

<div id="pins">
  <%= render @pins %>
</div>

<%= will_paginate @pins %>